### ISSUE TITLE
Can not be tested?

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [LTS4/DeepFool#3]
Hello,I have a question that when I save the adv_img using "plt.savefig('C:/Users/acer/Desktop/try/deepfool_adv_img.jpg')",then I put the path of the adv_img I have saved into input_path,but Original label doesn't changed,doesn't it should be the Adversarial label?And what makes this happens?
Thanks!

**Comment by iArunava** [comment]
While saving an image, you loose precision which is important, I haven't run the `deepfool` code yet (currently implementing) but as I have seen with other attacks, this is the case, as the image is perturbed, and the image say is in `float64` then while saving `plt.imsave` (haven't checked with `plt.savefig`) multiplies the image with `255` and then clips it most certainly. (to keep it between the range of `0-255`) and thus the precision is lost in the process. (float -> int)

P.S. I haven't found a yet found a way to save the perturbed matrix as an image.
That said you can always save the `np.ndarray` with `np.save` [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html) with all the precision you need. (Haven't experimented, but I am very certain)

**Comment by zhjikoshlizhzc** [comment]
Thanks a lot！I would try to use `np.save`.
